# Generated by Django 5.2.6 on 2025-09-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BribeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bribe_type', models.CharField(choices=[('known', 'Known'), ('unknown', 'Unknown')], max_length=10)),
                ('institution', models.CharField(max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('reporter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reporter_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
