# Generated by Django 5.2.6 on 2025-09-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bribereport',
            name='bribe_type',
        ),
        migrations.AddField(
            model_name='bribereport',
            name='ministry',
            field=models.CharField(choices=[('education', 'Ministry of Education'), ('health', 'Ministry of Health'), ('finance', 'Ministry of Finance and National Planning'), ('agriculture', 'Ministry of Agriculture'), ('justice', 'Ministry of Justice'), ('defence', 'Ministry of Defence'), ('home_affairs', 'Ministry of Home Affairs'), ('tourism', 'Ministry of Tourism'), ('energy', 'Ministry of Energy'), ('infrastructure', 'Ministry of Infrastructure and Housing'), ('labour', 'Ministry of Labour and Social Security'), ('mines', 'Ministry of Mines and Minerals Development'), ('transport', 'Ministry of Transport and Logistics'), ('youth', 'Ministry of Youth, Sport and Arts'), ('lands', 'Ministry of Lands and Natural Resources'), ('local_gov', 'Ministry of Local Government and Rural Development'), ('technology', 'Ministry of Technology and Science'), ('commerce', 'Ministry of Commerce, Trade and Industry')], default='lands', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bribereport',
            name='reason',
            field=models.CharField(default='unkonwn', max_length=255),
            preserve_default=False,
        ),
    ]
